In [1]:
df = pd.read_csv("movies.csv")

In [2]:
df

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,...,actors,description,avg_vote,votes,budget,usa_gross_income,worlwide_gross_income,metascore,reviews_from_users,reviews_from_critics
0,tt0002130,L'Inferno,L'Inferno,1911,1911-03-06,"Adventure, Drama, Fantasy",68,Italy,Italian,"Francesco Bertolini, Adolfo Padovan",...,"Salvatore Papa, Arturo Pirovano, Giuseppe de L...",Loosely adapted from Dante's Divine Comedy and...,7.0,2237,NaN,NaN,NaN,NaN,31.0,14.0
1,tt0003740,Cabiria,Cabiria,1914,1914-04-18,"Adventure, Drama, History",148,Italy,Italian,Giovanni Pastrone,...,"Carolina Catena, Lidia Quaranta, Gina Marangon...",Cabiria is a Roman child when her home is dest...,7.1,3073,$ 210000,NaN,NaN,NaN,31.0,26.0
2,tt0004707,Tillie's Punctured Romance,Tillie's Punctured Romance,1914,1914-12-21,Comedy,82,USA,"None, English","Mack Sennett, Charles Bennett",...,"Marie Dressler, Charles Chaplin, Mabel Normand...",A con man from the city dupes a wealthy countr...,6.3,3250,$ 50000,NaN,NaN,NaN,38.0,18.0
3,tt0004972,Nascita di una nazione,The Birth of a Nation,1915,1915-03-21,"Drama, History, War",195,USA,None,D.W. Griffith,...,"Henry B. Walthall, Lillian Gish, Mae Marsh, Mi...",The Stoneman family finds its friendship with ...,6.3,22213,$ 100000,NaN,NaN,NaN,368.0,97.0
4,tt0005078,The Cheat,The Cheat,1915,1915-12-13,"Drama, Romance",59,USA,English,Cecil B. DeMille,...,"Fannie Ward, Sessue Hayakawa, Jack Dean, James...","A venal, spoiled stockbroker's wife impulsivel...",6.6,2305,$ 17311,NaN,NaN,NaN,38.0,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20003,tt9831136,The Banana Splits Movie,The Banana Splits Movie,2019,2019-08-13,"Comedy, Horror, Sci-Fi",89,"USA, South Africa, Canada",English,Danishka Esterhazy,...,"Dani Kind, Steve Lund, Celina Martin, Finlay W...",A family attends a live taping of The Banana S...,5.0,2373,NaN,NaN,NaN,NaN,124.0,59.0
20004,tt9860728,Falling Inn Love - Ristrutturazione con amore,Falling Inn Love,2019,2019-08-29,"Comedy, Romance",98,USA,English,Roger Kumble,...,"Christina Milian, Adam Demos, Jeffrey Bowyer-C...",When city girl Gabriela spontaneously enters a...,5.6,14108,NaN,NaN,NaN,NaN,265.0,32.0
20005,tt9894470,VFW,VFW,2019,2020-02-14,"Action, Crime, Horror",92,USA,English,Joe Begos,...,"Stephen Lang, William Sadler, Fred Williamson,...",A group of old war veterans put their lives on...,6.1,4178,NaN,NaN,$ 23101,72.0,83.0,94.0
20006,tt9898858,Coffee & Kareem,Coffee & Kareem,2020,2020-04-03,"Action, Comedy",88,USA,English,Michael Dowse,...,"Ed Helms, Taraji P. Henson, Terrence Little Ga...",Twelve-year-old Kareem Manning hires a crimina...,5.1,10627,NaN,NaN,NaN,35.0,388.0,64.0
20007,tt9900782,Kaithi,Kaithi,2019,2019-10-25,"Action, Thriller",145,India,Tamil,Lokesh Kanagaraj,...,"Karthi, Narain, Ramana, George Maryan, Harish ...",A recently released prisoner becomes involved ...,8.5,8400,INR 240000000,NaN,$ 524061,NaN,188.0,8.0

In [26]:
df = df[df['votes']>2000]

In [27]:
df.to_csv('movies.csv', index=False)

In [ ]:
11.7

In [6]:
df.columns

Index(['imdb_title_id', 'title', 'original_title', 'year', 'date_published',
       'genre', 'duration', 'country', 'language', 'director', 'writer',
       'production_company', 'actors', 'description', 'avg_vote', 'votes',
       'budget', 'usa_gross_income', 'worlwide_gross_income', 'metascore',
       'reviews_from_users', 'reviews_from_critics'],
      dtype='object')

In [7]:
df[['imdb_title_id', 'title', 'original_title', 'year',
       'genre', 'director','actors', 'description', 'avg_vote', 'votes']]

,imdb_title_id,title,original_title,year,genre,director,actors,description,avg_vote,votes
0,tt0002130,L'Inferno,L'Inferno,1911,"Adventure, Drama, Fantasy","Francesco Bertolini, Adolfo Padovan","Salvatore Papa, Arturo Pirovano, Giuseppe de L...",Loosely adapted from Dante's Divine Comedy and...,7.0,2237
1,tt0003740,Cabiria,Cabiria,1914,"Adventure, Drama, History",Giovanni Pastrone,"Carolina Catena, Lidia Quaranta, Gina Marangon...",Cabiria is a Roman child when her home is dest...,7.1,3073
2,tt0004707,Tillie's Punctured Romance,Tillie's Punctured Romance,1914,Comedy,"Mack Sennett, Charles Bennett","Marie Dressler, Charles Chaplin, Mabel Normand...",A con man from the city dupes a wealthy countr...,6.3,3250
3,tt0004972,Nascita di una nazione,The Birth of a Nation,1915,"Drama, History, War",D.W. Griffith,"Henry B. Walthall, Lillian Gish, Mae Marsh, Mi...",The Stoneman family finds its friendship with ...,6.3,22213
4,tt0005078,The Cheat,The Cheat,1915,"Drama, Romance",Cecil B. DeMille,"Fannie Ward, Sessue Hayakawa, Jack Dean, James...","A venal, spoiled stockbroker's wife impulsivel...",6.6,2305
...,...,...,...,...,...,...,...,...,...,...
20003,tt9831136,The Banana Splits Movie,The Banana Splits Movie,2019,"Comedy, Horror, Sci-Fi",Danishka Esterhazy,"Dani Kind, Steve Lund, Celina Martin, Finlay W...",A family attends a live taping of The Banana S...,5.0,2373
20004,tt9860728,Falling Inn Love - Ristrutturazione con amore,Falling Inn Love,2019,"Comedy, Romance",Roger Kumble,"Christina Milian, Adam Demos, Jeffrey Bowyer-C...",When city girl Gabriela spontaneously enters a...,5.6,14108
20005,tt9894470,VFW,VFW,2019,"Action, Crime, Horror",Joe Begos,"Stephen Lang, William Sadler, Fred Williamson,...",A group of old war veterans put their lives on...,6.1,4178
20006,tt9898858,Coffee & Kareem,Coffee & Kareem,2020,"Action, Comedy",Michael Dowse,"Ed Helms, Taraji P. Henson, Terrence Little Ga...",Twelve-year-old Kareem Manning hires a crimina...,5.1,10627
20007,tt9900782,Kaithi,Kaithi,2019,"Action, Thriller",Lokesh Kanagaraj,"Karthi, Narain, Ramana, George Maryan, Harish ...",A recently released prisoner becomes involved ...,8.5,8400

In [8]:
df.to_csv("movies2.csv")

In [22]:
df = pd.read_csv("out.csv")

In [23]:
df

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,...,actors,description,avg_vote,votes,budget,usa_gross_income,worlwide_gross_income,metascore,reviews_from_users,reviews_from_critics
0,tt0002130,L'Inferno,L'Inferno,1911,1911-03-06,"Adventure, Drama, Fantasy",68,Italy,Italian,"Francesco Bertolini, Adolfo Padovan",...,"Salvatore Papa, Arturo Pirovano, Giuseppe de L...",Loosely adapted from Dante's Divine Comedy and...,7.0,2237,NaN,NaN,NaN,NaN,31.0,14.0
1,tt0003740,Cabiria,Cabiria,1914,1914-04-18,"Adventure, Drama, History",148,Italy,Italian,Giovanni Pastrone,...,"Carolina Catena, Lidia Quaranta, Gina Marangon...",Cabiria is a Roman child when her home is dest...,7.1,3073,$ 210000,NaN,NaN,NaN,31.0,26.0
2,tt0004707,Tillie's Punctured Romance,Tillie's Punctured Romance,1914,1914-12-21,Comedy,82,USA,"None, English","Mack Sennett, Charles Bennett",...,"Marie Dressler, Charles Chaplin, Mabel Normand...",A con man from the city dupes a wealthy countr...,6.3,3250,$ 50000,NaN,NaN,NaN,38.0,18.0
3,tt0004972,Nascita di una nazione,The Birth of a Nation,1915,1915-03-21,"Drama, History, War",195,USA,None,D.W. Griffith,...,"Henry B. Walthall, Lillian Gish, Mae Marsh, Mi...",The Stoneman family finds its friendship with ...,6.3,22213,$ 100000,NaN,NaN,NaN,368.0,97.0
4,tt0005078,The Cheat,The Cheat,1915,1915-12-13,"Drama, Romance",59,USA,English,Cecil B. DeMille,...,"Fannie Ward, Sessue Hayakawa, Jack Dean, James...","A venal, spoiled stockbroker's wife impulsivel...",6.6,2305,$ 17311,NaN,NaN,NaN,38.0,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20003,tt9831136,The Banana Splits Movie,The Banana Splits Movie,2019,2019-08-13,"Comedy, Horror, Sci-Fi",89,"USA, South Africa, Canada",English,Danishka Esterhazy,...,"Dani Kind, Steve Lund, Celina Martin, Finlay W...",A family attends a live taping of The Banana S...,5.0,2373,NaN,NaN,NaN,NaN,124.0,59.0
20004,tt9860728,Falling Inn Love - Ristrutturazione con amore,Falling Inn Love,2019,2019-08-29,"Comedy, Romance",98,USA,English,Roger Kumble,...,"Christina Milian, Adam Demos, Jeffrey Bowyer-C...",When city girl Gabriela spontaneously enters a...,5.6,14108,NaN,NaN,NaN,NaN,265.0,32.0
20005,tt9894470,VFW,VFW,2019,2020-02-14,"Action, Crime, Horror",92,USA,English,Joe Begos,...,"Stephen Lang, William Sadler, Fred Williamson,...",A group of old war veterans put their lives on...,6.1,4178,NaN,NaN,$ 23101,72.0,83.0,94.0
20006,tt9898858,Coffee & Kareem,Coffee & Kareem,2020,2020-04-03,"Action, Comedy",88,USA,English,Michael Dowse,...,"Ed Helms, Taraji P. Henson, Terrence Little Ga...",Twelve-year-old Kareem Manning hires a crimina...,5.1,10627,NaN,NaN,NaN,35.0,388.0,64.0
20007,tt9900782,Kaithi,Kaithi,2019,2019-10-25,"Action, Thriller",145,India,Tamil,Lokesh Kanagaraj,...,"Karthi, Narain, Ramana, George Maryan, Harish ...",A recently released prisoner becomes involved ...,8.5,8400,INR 240000000,NaN,$ 524061,NaN,188.0,8.0